name: Upload OpenAPI to ReadMe

on:
  push:
    branches:
      - feature/readmeio
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install ReadMe CLI
        run: npm install -g rdme
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build project
        run: ./gradlew build

      - name: Upload OpenAPI Spec
        run: echo "README changed? ${{secrets.README_API_KEY}} ${{ secrets.README_API_ID}} " |
          ./gradlew uploadApiSpec
        env:
          README_API_KEY: ${{ secrets.README_API_KEY}}
          README_API_ID: ${{ secrets.README_API_ID}}
